version: "3"
services:
  com.platformservices.budgetmetal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: complatformservicesbudgetmetal
    build:
      context: .
      dockerfile: Com.PlatformServices.BudgetMetal/Dockerfile
