version: '3'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: budgetmetaladmin
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile
    ports:
      - 9908:80

networks:
    dockernet:
        external: true
