version: '3'

services:

  platform_database_mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=platform_db
      - MYSQL_USER=platform_user
      - MYSQL_PASSWORD=password
    volumes:
      - #"/c/Users/Docker_Folder_Share/database:/var/lib/mysql" # windows development volume mapping
      - "./database:/var/lib/mysql" # production volume mapping
    ports:
      - 3306:3306